# Generated by Django 3.2.4 on 2021-06-28 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField(default='', max_length=56)),
                ('desc', models.TextField(default='', max_length=256)),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
