# Generated by Django 2.2.12 on 2021-06-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
