# Generated by Django 3.2.4 on 2021-06-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chip', '0002_auto_20210629_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
